# mongo-deploy.yaml

# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: employee-app
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
      tier: database
  template:
    metadata:
      labels:
        app: employee-app
        tier: database
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo-port
---
# MongoDB Service (ClusterIP for internal communication)
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: employee-app
    tier: database
spec:
  # ClusterIP is sufficient as only the NodeJS app needs to reach it
  type: ClusterIP 
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-port
  selector:
    app: employee-app
    tier: database
