#kubectl apply -f storage.yaml
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume1
  labels:
    type: local
    app: cps-postgres-db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cps-postgres-db-claim
  labels:
    app: cps-postgres-db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
